"""
End-to-end test of the AI filter with a realistic trade signal.
"""
import asyncio
import json
from src.ai.hermes_filter import HermesFilter
from src.ai.prompts import SYSTEM_PROMPT

SAMPLE_CONTEXT = """СИГНАЛ:
- Coin: ETH/USDT
- Direction: LONG
- Generated by: trend_follower_v1
- Entry: 2900.0
- Suggested stop: 2842.0
- Suggested TP1: 2958.0
- Suggested TP2: 3016.0
- Confidence: 0.75
- Reason: EMA50 golden cross EMA200, ADX=32.1

КОНТЕКСТ МОНЕТИ:
- ETH/USDT price now: 2895.0
- ETH/USDT 1d trend: bull
- ETH/USDT 4h trend: bull
- ETH/USDT 1h trend: pullback to EMA50
- ATR(14, 1h): 35.2
- ADX(4h): 32.1

КОНТЕКСТ BTC:
- BTC 1h change: +0.30%
- BTC 4h trend: bull

FUNDING та ЛІКВІДАЦІЇ:
- ETH/USDT funding rate: 0.0120% / 8h
- ETH/USDT liquidations 1h: $12000000

НОВИНИ (24h):
- BlackRock ETF inflow $200M (positive)

СТАН БОТА:
- Drawdown today: -1.5%
- Loss streak: 1
- Win rate (last 30): 58.0%
- Avg R (last 30): +0.32
- Open positions: 1/3
- Open LONG positions: 1

Прийми рішення."""


async def main():
    ai = HermesFilter()
    print("Sending signal to Hermes AI filter...")
    result = await ai.evaluate(SAMPLE_CONTEXT)
    print("\nAI Decision:")
    print(json.dumps(result, ensure_ascii=False, indent=2))


asyncio.run(main())
